import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import jsonpatch from 'fast-json-patch';
import type { Operation } from 'fast-json-patch';
import { BuildSpecError, compileBuildSpec } from '@minecraft-schematic-lab/block-compiler';
import type { BuildSpec } from '@minecraft-schematic-lab/build-spec';
import { newBuildId, newSessionId } from '@minecraft-schematic-lab/shared';
import type {
  ApplyPatchResponse,
  BranchInfo,
  BuildResult,
  BuildStats,
  CurrentBuildResponse,
  InitGitResult,
  InitLocalResult,
  PreviewData,
  ProjectStatus,
  PushResult,
  SaveVersionResult,
  SessionSummary,
  ValidationResult,
  Vec3Size,
} from '@minecraft-schematic-lab/shared';
import type { AppConfig } from '../config';
import { HttpError } from '../httpError';
import { renderIsometric } from '../render/renderIsometric';
import { unsupportedLegacyBlocks, writeMcEditSchematic } from '../schematic/writeMcEditSchematic';
import { writeSpongeSchematic } from '../schematic/writeSpongeSchematic';
import type { SchematicFormat } from '../schematic/schematicTypes';
import type { Session } from './types';
import type { GitProjectService } from '../git/GitProjectService';

const { applyPatch, deepClone } = jsonpatch;

const EMPTY_SIZE: Vec3Size = { x: 0, y: 0, z: 0 };

function safeFilename(name: string): string {
  const cleaned = name
    .trim()
    .replace(/[^A-Za-z0-9-_]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
  return cleaned || 'schematic';
}

function projectReadme(session: Session): string {
  const name = session.spec?.name ?? 'Schematic';
  return [
    `# ${name}`,
    '',
    'Generated by [minecraft-schematic-lab](https://github.com/SimoneRecchia/minecraft-schematic-lab).',
    '',
    `- Blocks: ${session.blockCount}`,
    `- Palette: ${session.palette.join(', ') || '—'}`,
    '',
    'Load the `.schem` with WorldEdit: `//schem load <name>` then `//paste`.',
    '',
  ].join('\n');
}

export class SessionManager {
  private readonly sessions = new Map<string, Session>();
  private currentId = '';

  constructor(
    private readonly config: AppConfig,
    private readonly git: GitProjectService,
  ) {
    this.createSession();
  }

  private now(): number {
    return Date.now();
  }

  createSession(): Session {
    const id = newSessionId();
    const ts = this.now();
    const session: Session = {
      id,
      buildId: null,
      spec: null,
      volume: null,
      warnings: [],
      blockCount: 0,
      palette: [],
      blockEntities: [],
      schematicCache: new Map(),
      project: { mode: 'memory', path: null, git: null },
      createdAt: ts,
      updatedAt: ts,
    };
    this.sessions.set(id, session);
    this.currentId = id;
    return session;
  }

  getCurrent(): Session {
    const session = this.sessions.get(this.currentId);
    if (!session) throw new HttpError(500, 'No active session.');
    return session;
  }

  list(): SessionSummary[] {
    return [...this.sessions.values()].map((s) => ({
      sessionId: s.id,
      name: s.spec?.name ?? 'Untitled',
      buildId: s.buildId,
      blockCount: s.blockCount,
      isCurrent: s.id === this.currentId,
    }));
  }

  select(id: string): void {
    if (!this.sessions.has(id)) throw new HttpError(404, `Session not found: ${id}`);
    this.currentId = id;
  }

  deleteSession(id: string): void {
    if (!this.sessions.has(id)) throw new HttpError(404, `Session not found: ${id}`);
    this.sessions.delete(id);
    if (this.currentId === id) {
      const next = this.sessions.keys().next();
      if (next.done) this.createSession();
      else this.currentId = next.value;
    }
  }

  build(input: unknown): BuildResult {
    const session = this.getCurrent();
    try {
      const result = compileBuildSpec(input);
      if (/^1\.12(?:\.|$)/.test(result.spec.minecraftVersion)) {
        const unsupported = unsupportedLegacyBlocks(result.volume);
        if (unsupported.length)
          throw new BuildSpecError([
            `无法无损导出为 Minecraft 1.12.2，请更换或补充兼容映射：${unsupported.join(', ')}`,
          ]);
      }
      session.spec = result.spec;
      session.volume = result.volume;
      session.warnings = result.warnings;
      session.blockCount = result.blockCount;
      session.palette = result.palette;
      session.blockEntities = result.blockEntities;
      session.buildId = newBuildId();
      session.schematicCache.clear();
      session.updatedAt = this.now();
      return {
        sessionId: session.id,
        buildId: session.buildId,
        valid: true,
        errors: [],
        warnings: result.warnings,
        blockCount: result.blockCount,
        palette: result.palette,
        previewData: this.previewFor(session),
      };
    } catch (error) {
      if (error instanceof BuildSpecError) {
        return {
          sessionId: session.id,
          buildId: session.buildId,
          valid: false,
          errors: error.errors,
          warnings: [],
          blockCount: 0,
          palette: [],
          previewData: this.previewFor(session),
        };
      }
      throw error;
    }
  }

  validate(input: unknown): ValidationResult {
    try {
      const result = compileBuildSpec(input);
      if (/^1\.12(?:\.|$)/.test(result.spec.minecraftVersion)) {
        const unsupported = unsupportedLegacyBlocks(result.volume);
        if (unsupported.length)
          throw new BuildSpecError([
            `无法无损导出为 Minecraft 1.12.2，请更换或补充兼容映射：${unsupported.join(', ')}`,
          ]);
      }
      return { valid: true, errors: [], warnings: result.warnings };
    } catch (error) {
      if (error instanceof BuildSpecError) {
        return { valid: false, errors: error.errors, warnings: [] };
      }
      throw error;
    }
  }

  applyPatch(patch: unknown): ApplyPatchResponse {
    const session = this.getCurrent();
    if (!session.spec) {
      throw new HttpError(409, 'No current build to patch. Create a build first.');
    }
    if (!Array.isArray(patch)) {
      throw new HttpError(400, 'Patch must be a JSON Patch (RFC 6902) array.');
    }
    const next = applyPatch(deepClone(session.spec), patch as Operation[], true, false).newDocument;
    const result = this.build(next);
    if (!result.valid) {
      throw new HttpError(422, `Patched spec is invalid: ${result.errors.join('; ')}`);
    }
    return {
      spec: session.spec as BuildSpec,
      valid: true,
      errors: [],
      warnings: result.warnings,
      stats: this.statsFor(session),
      previewUrl: this.previewUrl(),
    };
  }

  current(): CurrentBuildResponse {
    const session = this.getCurrent();
    return {
      sessionId: session.id,
      buildId: session.buildId,
      spec: session.spec,
      stats: this.statsFor(session),
      warnings: session.warnings,
      previewUrl: this.previewUrl(),
      project: this.projectStatus(),
    };
  }

  getPreviewData(): PreviewData {
    return this.previewFor(this.getCurrent());
  }

  async renderImage(): Promise<Buffer> {
    const session = this.getCurrent();
    if (!session.volume) {
      throw new HttpError(409, 'Nothing to render yet. Create a build first.');
    }
    return renderIsometric(session.volume);
  }

  async exportSchematic(
    format: SchematicFormat = 'sponge-v2',
  ): Promise<{ buffer: Buffer; filename: string }> {
    const session = this.getCurrent();
    if (!session.spec || !session.volume) {
      throw new HttpError(409, 'Nothing to export yet. Create a build first.');
    }
    const buffer = await this.schematicFor(session, format);
    const extension = format === 'mcedit' ? 'schematic' : 'schem';
    const filename = `${safeFilename(session.spec.name || session.spec.id)}.${extension}`;
    return { buffer, filename };
  }

  projectStatus(): ProjectStatus {
    const session = this.getCurrent();
    return {
      mode: session.project.mode,
      path: session.project.path,
      git: session.project.git
        ? {
            branch: session.project.git.branch,
            branches: session.project.git.branches,
            remote: session.project.git.remote,
          }
        : null,
    };
  }

  async initLocalProject(path: string): Promise<InitLocalResult> {
    const dir = this.git.resolveSafePath(path);
    this.git.ensureDir(dir);
    const session = this.getCurrent();
    session.project = { mode: 'local', path: dir, git: null };
    await this.writeProjectFiles(session, dir);
    return { mode: 'local', path: dir };
  }

  async initGitProject(
    path: string,
    userName?: string,
    userEmail?: string,
  ): Promise<InitGitResult> {
    await this.git.checkGitAvailable();
    const dir = this.git.resolveSafePath(path);
    this.git.ensureDir(dir);
    if (!(await this.git.isRepo(dir))) {
      await this.git.initRepo(dir);
    }
    const identity = await this.git.readLocalIdentity(dir);
    await this.git.setLocalIdentity(
      dir,
      userName ?? identity.name ?? 'minecraft-schematic-lab',
      userEmail ?? identity.email ?? 'schematic-lab@localhost',
    );
    const session = this.getCurrent();
    await this.writeProjectFiles(session, dir);
    await this.git.commitAll(dir, 'Initialize schematic project');
    const branch = await this.git.currentBranch(dir);
    const branches = await this.git.listBranches(dir);
    session.project = { mode: 'git', path: dir, git: { branch, branches, remote: null } };
    return { mode: 'git', path: dir, branch };
  }

  async saveVersion(message: string): Promise<SaveVersionResult> {
    const session = this.requireGitPath();
    const dir = session.project.path as string;
    await this.writeProjectFiles(session, dir);
    const result = await this.git.commitAll(dir, message || 'Update schematic');
    await this.refreshGitInfo(session);
    return { committed: result.committed, commit: result.commit, message };
  }

  async branches(): Promise<BranchInfo> {
    const session = this.requireGitPath();
    const dir = session.project.path as string;
    return {
      current: await this.git.currentBranch(dir),
      branches: await this.git.listBranches(dir),
    };
  }

  async branch(name: string, create = false): Promise<BranchInfo> {
    const session = this.requireGitPath();
    const dir = session.project.path as string;
    if (create) await this.git.createBranch(dir, name);
    await this.git.checkoutBranch(dir, name);
    await this.refreshGitInfo(session);
    return {
      current: await this.git.currentBranch(dir),
      branches: await this.git.listBranches(dir),
    };
  }

  async push(remote = 'origin', remoteUrl?: string): Promise<PushResult> {
    const session = this.requireGitPath();
    const dir = session.project.path as string;
    if (remoteUrl) await this.git.setRemote(dir, remote, remoteUrl);
    const branch = (await this.git.currentBranch(dir)) ?? 'main';
    const output = await this.git.push(dir, remote, branch);
    if (session.project.git) session.project.git.remote = remote;
    return { ok: true, output };
  }

  private requireGitPath(): Session {
    const session = this.getCurrent();
    if (session.project.mode !== 'git' || !session.project.path) {
      throw new HttpError(409, 'No git project. Initialize one first with init_git_project.');
    }
    return session;
  }

  private async refreshGitInfo(session: Session): Promise<void> {
    const dir = session.project.path;
    if (!dir) return;
    session.project.git = {
      branch: await this.git.currentBranch(dir),
      branches: await this.git.listBranches(dir),
      remote: session.project.git?.remote ?? null,
    };
  }

  private async writeProjectFiles(session: Session, dir: string): Promise<void> {
    if (!session.spec || !session.volume) return;
    this.git.writeFiles(dir, {
      'build-spec.json': `${JSON.stringify(session.spec, null, 2)}\n`,
      'README.md': projectReadme(session),
      '.gitignore': 'node_modules/\n',
    });
    const buffer = await this.schematicFor(session, 'sponge-v2');
    writeFileSync(join(dir, `${safeFilename(session.spec.name || session.spec.id)}.schem`), buffer);
  }

  private async schematicFor(
    session: Session,
    format: SchematicFormat = 'sponge-v2',
  ): Promise<Buffer> {
    const cached = session.schematicCache.get(format);
    if (cached) return cached;
    if (!session.spec || !session.volume) {
      throw new HttpError(409, 'Nothing to export yet. Create a build first.');
    }
    const buffer =
      format === 'mcedit'
        ? await writeMcEditSchematic(session.volume, session.blockEntities)
        : await writeSpongeSchematic(session.spec, session.volume, {
            version: format === 'sponge-v3' ? 3 : 2,
            blockEntities: session.blockEntities,
          });
    session.schematicCache.set(format, buffer);
    return buffer;
  }

  private previewFor(session: Session): PreviewData {
    if (!session.volume) return { size: EMPTY_SIZE, instances: {} };
    return {
      size: { x: session.volume.x, y: session.volume.y, z: session.volume.z },
      instances: session.volume.toInstanceGroups(),
    };
  }

  private statsFor(session: Session): BuildStats {
    return {
      blockCount: session.blockCount,
      palette: session.palette,
      size: session.volume
        ? { x: session.volume.x, y: session.volume.y, z: session.volume.z }
        : EMPTY_SIZE,
    };
  }

  private previewUrl(): string {
    return `${this.config.baseUrl}/`;
  }
}
